LoggingMonkey.Web/Models/DisplayOptionsModel.cs
using System;
using System.Web;
using System.Web.Helpers;
using LoggingMonkey.Web.Helpers;

namespace LoggingMonkey.Web.Models
{
    public class DisplayOptionsModel
    {
        public DateFormatTypes DateFormatType { get; set; }

        public string ThemeName { get; set; }

        public bool UseTinyFont { get; set; }

        public bool ShowCats { get; set; }

        public static DisplayOptionsModel FromHttpContext(HttpContextBase context)
        {
            return context.Request.Cookies["LoggingMonkeyDisplay"] != null
                       ? FromJson(context.Request.Cookies["LoggingMonkeyDisplay"].Value)
                       : new DisplayOptionsModel();
        }

        public static string ToJson(DisplayOptionsModel model)
        {
            return Json.Encode(model);
        }

        public static DisplayOptionsModel FromJson(string val)
        {
            return String.IsNullOrWhiteSpace(val) ? null : Json.Decode<DisplayOptionsModel>(val);
        }
    }
}

LoggingMonkey.Web/Models/IndexViewModel.cs
namespace LoggingMonkey.Web.Models
{
    public class IndexViewModel
    {
        public SearchModel Search { get; set; }
        public DisplayOptionsModel DisplayOptions { get; set; }
        public MessagesModel Messages { get; set; }
    }
}

LoggingMonkey.Web/Models/MessagesModel.cs
using System.Collections.Generic;
using System;
using System.Linq;

namespace LoggingMonkey.Web.Models
{
    public class Message
    {
        public Message()
        {
            Lines = new List<string>();
        }

        public bool UsesTor { get; set; }
        public DateTime Timestamp { get; set; }
        public string Nick;
        public FastLogReader.LineType Type;
        public List<string> Lines;
    }

    public class MessagesModel
    {
        public MessagesModel()
        {
            Messages = new List<Message>();
        }

        public string ChannelName { get; set; }

        public decimal TimeElapsed { get; set; }

        public List<Message> Messages { get; set; }

        public bool IsEmpty
        {
            get
            {
                return Messages.Count == 0;
            }
        }

        public IEnumerable<string> ActiveNicks
        {
            get { return Messages.Select(x => x.Nick).Distinct(); }
        }
    }
}

LoggingMonkey.Web/Models/SearchModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using LoggingMonkey.Web.Helpers;

namespace LoggingMonkey.Web.Models
{
	public class SearchModel
	{
        public SearchModel()
        {
            ChannelId = 1;
        }

        public string Nickname { get; set; }
        public string Username { get; set; }
        public string Hostname { get; set; }

        public string Message { get; set; }
        public int ChannelId { get; set; }

        [Display(Name = "From")]
        public DateTime? FromDate { get; set; }

        [Display(Name = "To")]
        public DateTime? ToDate { get; set; }

        public MatchTypes MatchType { get; set; }
        public bool IsCaseSensitive { get; set; }

        public uint Context { get; set; }

	    public bool IsAdvancedSearch
	    {
            get
            {
                return !String.IsNullOrWhiteSpace(Username) || !String.IsNullOrWhiteSpace(Hostname) || FromDate.HasValue ||
                       ToDate.HasValue || MatchType != MatchTypes.PlainText || IsCaseSensitive || Context != 0;
            }
	    }
	}
}

LoggingMonkey.Web/Controllers/MainController.cs
using System;
using System.Globalization;
using System.IO;
using System.IO.Packaging;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Http;
using LoggingMonkey.Web.Helpers;
using LoggingMonkey.Web.Models;

namespace LoggingMonkey.Web.Controllers
{
    using HttpGet  = System.Web.Mvc.HttpGetAttribute;
    using HttpPost = System.Web.Mvc.HttpPostAttribute;

    public class MainController : Controller
    {
        private DateTime? ConvertQueryValueToDate(string qs)
        {
            var dateString = Request.QueryString[qs];

            if (dateString == null)
            {
                return null;
            }

            DateTime date;

            var successful = DateTime.TryParse(dateString, out date) ||
                             DateTime.TryParseExact(dateString, "M/d h:mm tt", null, DateTimeStyles.None, out date);

            return successful ? date : (DateTime?)null;
        }

        [HttpGet]
        //[Whitelisted]
        public void Index([FromUri] SearchModel model)
        {
            Response.Buffer = false;
            Response.BufferOutput = false;

            var displayOptions = DisplayOptionsModel.FromHttpContext(HttpContext);

            model.FromDate = ConvertQueryValueToDate("FromDate");
            model.ToDate   = ConvertQueryValueToDate("ToDate");

            var messages = MessageRetriever.Get(model);
            var vm       = new IndexViewModel { Search = model, DisplayOptions = displayOptions, Messages = messages };

            UnbufferedRenderer.Render(ControllerContext, ViewData, TempData, Response, vm);
        }

        [HttpPost]
        public ActionResult UpdateDisplayOptions(DisplayOptionsModel model)
        {
            var cookie = new HttpCookie("LoggingMonkeyDisplay", DisplayOptionsModel.ToJson(model));
            Response.Cookies.Set(cookie);

            return Request.UrlReferrer != null ? (ActionResult)Redirect(Request.UrlReferrer.AbsoluteUri) : RedirectToAction("Index");
        }

        [HttpGet]
        [Whitelisted]
        public ActionResult Backup()
        {
            Stream zip;

            try
            {
                zip = System.IO.File.Open(Paths.BackupZip, FileMode.Create, FileAccess.ReadWrite, FileShare.None);
            }
            catch (IOException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.ServiceUnavailable);
            }

            using (zip)
            {
                using (var package = Package.Open(zip, FileMode.Create))
                {
                    var files = Directory.GetFiles(Paths.LogsDirectory, "*.log", SearchOption.TopDirectoryOnly);

                    foreach (var file in files)
                    {
                        var relFile = Uri.EscapeDataString(Path.GetFileName(file));
                        var uri = PackUriHelper.CreatePartUri(new Uri(relFile, UriKind.Relative));
                        var part = package.CreatePart(uri, System.Net.Mime.MediaTypeNames.Text.Plain,
                                                      CompressionOption.Maximum);
                        
                        using (var fstream = System.IO.File.Open(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                        {
                            using (var partstream = part.GetStream())
                            {
                                fstream.CopyTo(partstream);
                            }
                        }

                        package.Flush();
                    }

                    package.Close();
                }

                zip.Flush();
                zip.Position = 0;

                var name = String.Format("LoggingMonkey Backup {0}.zip", DateTime.Now.ToString("M-d-yy h.mm tt"));

                return new FilePathResult(Paths.BackupZip, "applicaton/zip") {FileDownloadName = name};
            }
        }

        [HttpGet]
        public ActionResult Auth(string token)
        {
            var cookie = new HttpCookie(Program.AuthCookieName, token) {Expires = DateTime.Now.AddYears(10)};

            Response.Cookies.Add(cookie);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Denied()
        {
            switch (Cookie2AccessControlStatus.Convert(HttpContext))
            {
                case AccessControlStatus.Blacklisted:
                    ViewBag.Message = "Your account is blacklisted.";
                    break;

                case AccessControlStatus.Pending:
                    ViewBag.Message = "Pending whitelist approval.";
                    break;

                case AccessControlStatus.Error:
                    ViewBag.Message = "An unknown error occured.";
                    break;

                case AccessControlStatus.Whitelisted:
                    ViewBag.Message = "You shouldn't be here.";
                    break;
            }

            return View();
        }
    }
}

LoggingMonkey.Web/Views/Main/Denied.cshtml
@{
    ViewBag.Title = "Denied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<article>
    <h1>LoggingMonkey</h1>
    <p>@ViewBag.Message</p>
</article>

LoggingMonkey.Web/Views/Main/Index.cshtml
@using System.Threading
@using LoggingMonkey.Web.Helpers

@model LoggingMonkey.Web.Models.IndexViewModel

@{
    ViewBag.Title = "LoggingMonkey";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/ba-linkify.min.js"></script>
    <script type="text/javascript" src="~/Scripts/URI.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-timepicker-addon.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            LoggingMonkey(@Html.Raw(Json.Encode(Model.DisplayOptions.DateFormatType)));

            if ("@Model.Search.IsAdvancedSearch" === "True") {
                setTimeout(function() {
                    $('#showOptions').click();
                }, 200);
            }
        });
    </script>
}

<article>
    <h1><a href="/" title="Back to the jungle">LoggingMonkey</a></h1>

    @Html.Partial("_SearchForm", Model.Search)

    <div id="displayOptions">
        <hr style="border-top: 1px dashed #eee; border-bottom: 0; border-left: 0; margin-top: 20px;" />
        <h3>Display Options</h3>
        @Html.Partial("_DisplayOptionsForm", Model.DisplayOptions)
        <hr style="margin-top: 20px; border-top: 1px dashed #eee; border-bottom: 0; border-left: 0;" />
    </div>
    
    @{
        Response.Flush();
        Response.OutputStream.Flush();
    }

    
    @if (Model.Messages.IsEmpty)
    {
        <p>There don't seem to be any messages....</p>
    }
    else
    {
        @Html.RenderHeading(Model.Search)

        <div class="entries clearfix">
            @for (var i = 0; i < Model.Messages.Messages.Count; i++)
            {
                @Html.RenderMessage(Model.Messages.Messages[i])
                
                if (i % 100 == 0)
                {
                    Response.Flush();
                    Response.OutputStream.Flush();
                    Thread.Sleep(5000);
                }
            }
        </div>
    }
</article>

<footer>
    <p>
    Contact <b>MaulingMonkey</b> in #gamedev on AfterNET
    <br/>
    <span class="big-label">
        Connect with <a href="http://www.gamedev.net/community/chat/">java web client</a> or <a href="irc://irc.afternet.org/gamedev">launch desktop client</a>
    </span>
    <br/>
    <a href="#">GitHub</a> | <a href="#"><i class="icon-keyboard"></i></a> | UI by <b>Jovan</b>
    </p>
</footer>

LoggingMonkey.Web/Views/Main/MessageTypes/Action.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="action-entry"><span style="font-weight: bold;">@Model.Nick</span> @Model.Lines.First()</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Main/MessageTypes/Join.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="notice"><span style="font-weight: bold;">@Model.Nick</span> has joined the channel.</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Main/MessageTypes/Message.cshtml
@using LoggingMonkey.Web.Helpers
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="date">@Html.GetDateFromDisplayOptions(Model.Timestamp)</div>
    <div class="said-by"><span style="font-weight: bold;">@Model.Nick</span></div>
    <div class="message">
        @for (var i = 0; i < Model.Lines.Count; i++)
        {
            <p>@Model.Lines[i]</p>
            
            if (i != Model.Lines.Count - 1)
            {
                <hr />
            }
        }
    </div>
</div>

LoggingMonkey.Web/Views/Main/MessageTypes/Meta.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="meta-entry"><span style="font-weight: bold;">@Model.Nick</span> @Model.Lines.First()</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Main/MessageTypes/Quit.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="notice"><span style="font-weight: bold;">@Model.Nick</span> has quit.</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Main/_DisplayOptionsForm.cshtml
@using LoggingMonkey.Web.Helpers
@model LoggingMonkey.Web.Models.DisplayOptionsModel

@using (Html.BeginForm("UpdateDisplayOptions", "Main", FormMethod.Post, new {id = "formDisplayOptions"}))
{
    <label style="margin-left: 22px; margin-right: 15px;">Theme</label>
    @Html.DropDownListFor(x => x.ThemeName, Html.ThemesList())

    <label style="margin-left: 22px; margin-right: 15px;">Date Format</label>
    @Html.DropDownListFor(x => x.DateFormatType, Html.DateFormatTypesList())

	<label style="margin-left: 22px; margin-right: 5px;">@Html.CheckBoxFor(x => x.UseTinyFont) Use Tiny Font</label>
    <label style="margin-left: 22px; margin-right: 5px;">@Html.CheckBoxFor(x => x.ShowCats) A Cat Is Fine Too</label>
    
    <button type="submit">Save</button>
}

LoggingMonkey.Web/Views/Main/_SearchForm.cshtml
@model LoggingMonkey.Web.Models.SearchModel
@using LoggingMonkey.Web.Helpers

@using (Html.BeginForm("Index", "Main", FormMethod.Get, new { id = "homeForm" }))
{
	@Html.TextBoxFor(x => x.Nickname, new { placeholder = "nick", autofocus = true })
	<span class="madlib-label">said</span>
	@Html.TextBoxFor(x => x.Message, new { placeholder = "message" })
    <span class="madlib-label">in</span>
    @Html.DropDownListFor(x => x.ChannelId, Html.ChannelsList())
	
	<button type="submit">Search</button>
	
	<p class="right"><a href="#" id="showOptions"><i class="icon-chevron-sign-right"></i> More Options</a></p>
	
	<div id="advancedSearch" class="clearfix">
		<h3 style="margin-top: 0;">Advanced Search Options</h3>

		<section>
			<div class="controls">
				@Html.LabelFor(x => x.Username)
				@Html.TextBoxFor(x => x.Username)
			</div>
			<div  class="controls">
				@Html.LabelFor(x => x.Hostname)
				@Html.TextBoxFor(x => x.Hostname)
			</div>
		</section>

	    <section>
	        <div class="controls">
	            @Html.LabelFor(x => x.FromDate)
	            @Html.TextBoxFor(x => x.FromDate, new {@class = "datetimepicker", @Value = Html.GetDateFromDisplayOptions(Model.FromDate)})
	            <i style="position: relative; left: -25px; top: -1px;" class="icon-calendar"></i>
	        </div>
	        <div class="controls">
	            @Html.LabelFor(x => x.ToDate)
	            @Html.TextBoxFor(x => x.ToDate, new {@class = "datetimepicker", @Value = Html.GetDateFromDisplayOptions(Model.ToDate)})
	            <i style="position: relative; left: -25px; top: -1px;" class="icon-calendar"></i>
	        </div>
	    </section>
        
	    <section id="matchCaseOptions">
	        <div class="controls">
	            <label>Match using</label>
	            @Html.DropDownListFor(x => x.MatchType, Html.MatchTypesList())
	        </div>
	        <div id="caseSensitiveOption" class="controls">
	            <label><input type="checkbox" /> Case Sensitive</label>
	        </div>
	    </section>
        
	    <section style="clear:both; margin-top: 15px;">
	        <div class="controls">
	            @Html.LabelFor(x => x.Context)
                @Html.TextBoxFor(x => x.Context)
	        </div>
	    </section> 
	</div>
}

LoggingMonkey.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf8">

        <title>@ViewBag.Title</title>
        <link href="~/Content/css/normalize.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/redmond/jquery-ui.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/jquery-ui-timepicker-addon.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/main.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        @RenderBody()
        @RenderSection("scripts", required: false)
    </body>
</html>

LoggingMonkey.Web/Views/Unbuffered/Footer.cshtml
@model LoggingMonkey.Web.Models.IndexViewModel


    <footer>
        <p>
        Contact <b>MaulingMonkey</b> in #gamedev on AfterNET
        <br/>
        <span class="big-label">
            Connect with <a href="http://www.gamedev.net/community/chat/">java web client</a> or <a href="irc://irc.afternet.org/gamedev">launch desktop client</a>
        </span>
        <br/>
        <a href="#">GitHub</a> | <a href="#"><i class="icon-keyboard"></i></a> | UI by <b>Jovan</b>
        </p>
    </footer>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/ba-linkify.min.js"></script>
    <script type="text/javascript" src="~/Scripts/URI.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-ui-timepicker-addon.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    
    <script type="text/javascript">
        $(document).ready(function() {
            LoggingMonkey(@Html.Raw(Json.Encode(Model.DisplayOptions)));

            if ("@Model.Search.IsAdvancedSearch" === "True") {
                setTimeout(function() {
                    $('#showOptions').click();
                }, 800);
            }
        });
    </script>
</body>
</html>

LoggingMonkey.Web/Views/Unbuffered/Header.cshtml
@model LoggingMonkey.Web.Models.IndexViewModel

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf8">

        <title>@ViewBag.Title</title>
        <link href="~/Content/css/normalize.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/redmond/jquery-ui.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/jquery-ui-timepicker-addon.css" rel="stylesheet" type="text/css">
        <link href="~/Content/css/main.css" rel="stylesheet" type="text/css">
        
        @if (Model.DisplayOptions.UseTinyFont)
        {
            <style>
                @@font-face {
                    font-family: "04b03";
                    src: url("/Content/font/04B_03__.TTF") format("truetype");
                }
		        * {
		            font-family: "04b03";
                    font-size: 8px;
		        }
                h1 a {
                    font-family: 'Pacifico' !important;
                    font-size: 12px !important;
                }
                input, select {
                    font-size: 10px !important;
                }
                #caseSensitiveOption {
                    margin-top: -10px;
                    margin-left: 20px;
                }
                .said-by {
                    padding-right: 0;
                }
            </style>
        }
    </head>
    <body>

LoggingMonkey.Web/Views/Unbuffered/MessageTypes/Action.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="action-entry"><span style="font-weight: bold;">@Model.Nick</span> @Model.Lines.First()</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Unbuffered/MessageTypes/Join.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="notice"><span style="font-weight: bold;">@Model.Nick</span> has joined the channel.</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Unbuffered/MessageTypes/Message.cshtml
@using LoggingMonkey.Web.Helpers
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="date">@Html.GetDateFromDisplayOptions(Model.Timestamp)</div>
    <div class="said-by">
        <span style="font-weight: bold;">@Model.Nick</span>
        @if (Model.UsesTor)
        {
            @(" / TOR")
        }
    </div>
    <div class="message">
        @for (var i = 0; i < Model.Lines.Count; i++)
        {
            <p>@Model.Lines[i]</p>
            
            if (i != Model.Lines.Count - 1)
            {
                <hr />
            }
        }
    </div>
</div>

LoggingMonkey.Web/Views/Unbuffered/MessageTypes/Meta.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="meta-entry"><span style="font-weight: bold;">@Model.Nick</span> @Model.Lines.First()</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Unbuffered/MessageTypes/Quit.cshtml
@model LoggingMonkey.Web.Models.Message

<div class="log-entry clearfix">
    <div class="notice"><span style="font-weight: bold;">@Model.Nick</span> has quit.</div>
</div>

<div class="log-entry empty-entry"></div>

LoggingMonkey.Web/Views/Unbuffered/PostMessages.cshtml
@model LoggingMonkey.Web.Models.IndexViewModel

        </div>
</article>

LoggingMonkey.Web/Views/Unbuffered/PreMessages.cshtml
@using LoggingMonkey.Web.Helpers
@model LoggingMonkey.Web.Models.IndexViewModel

<article>
    <h1><a href="/" title="Back to the jungle">LoggingMonkey</a></h1>

    @Html.Partial("_SearchForm", Model.Search)

    <div id="displayOptions">
        <hr style="border-top: 1px dashed #eee; border-bottom: 0; border-left: 0; margin-top: 20px;" />
        <h3>Display Options</h3>
        @Html.Partial("_DisplayOptionsForm", Model.DisplayOptions)
        <hr style="margin-top: 20px; border-top: 1px dashed #eee; border-bottom: 0; border-left: 0;" />
    </div>
    
    @Html.RenderHeading(Model.Search)

    <div class="entries clearfix">

LoggingMonkey.Web/Views/Unbuffered/_DisplayOptionsForm.cshtml
@using LoggingMonkey.Web.Helpers
@model LoggingMonkey.Web.Models.DisplayOptionsModel

@using (Html.BeginForm("UpdateDisplayOptions", "Main"))
{
    <label style="margin-left: 22px; margin-right: 15px;">Date Format</label>
    @Html.DropDownListFor(x => x.DateFormatType, Html.DateFormatTypesList())

    <label style="margin-left: 22px; margin-right: 15px;">Theme</label>
    @Html.DropDownListFor(x => x.ThemeName, Html.ThemesList())

    <button type="submit">Save</button>
}

LoggingMonkey.Web/Views/Unbuffered/_SearchForm.cshtml
@model LoggingMonkey.Web.Models.SearchModel
@using LoggingMonkey.Web.Helpers

@using (Html.BeginForm("Index", "Main", FormMethod.Get, new { id = "homeForm" }))
{
	@Html.TextBoxFor(x => x.Nickname, new { placeholder = "nick", autofocus = true })
	<span class="madlib-label">said</span>
	@Html.TextBoxFor(x => x.Message, new { placeholder = "message" })
    <span class="madlib-label">in</span>
    @Html.DropDownListFor(x => x.ChannelId, Html.ChannelsList())
	
	<button type="submit">Search</button>
	
	<p class="right"><a href="#" id="showOptions"><i class="icon-chevron-sign-right"></i> More Options</a></p>
	
	<div id="advancedSearch" class="clearfix">
		<h3 style="margin-top: 0;">Advanced Search Options</h3>

		<section>
			<div class="controls">
				@Html.LabelFor(x => x.Username)
				@Html.TextBoxFor(x => x.Username)
			</div>
			<div  class="controls">
				@Html.LabelFor(x => x.Hostname)
				@Html.TextBoxFor(x => x.Hostname)
			</div>
		</section>

		<section>
			<div class="controls">
				@Html.LabelFor(x => x.FromDate)
				@Html.TextBoxFor(x => x.FromDate, new {@class = "datetimepicker", @Value = Html.GetDateFromDisplayOptions(Model.FromDate)})
				<i style="position: relative; left: -25px; top: -1px;" class="icon-calendar"></i>
			</div>
			<div class="controls">
				@Html.LabelFor(x => x.ToDate)
				@Html.TextBoxFor(x => x.ToDate, new {@class = "datetimepicker", @Value = Html.GetDateFromDisplayOptions(Model.ToDate)})
				<i style="position: relative; left: -25px; top: -1px;" class="icon-calendar"></i>
			</div>
		</section>
		  
		<section id="matchCaseOptions">
			<div class="controls">
				<label>Match using</label>
			    @Html.DropDownListFor(x => x.MatchType, Html.MatchTypesList())
			</div>
			<div id="caseSensitiveOption" class="controls">
				<label><input type="checkbox" /> Case Sensitive</label>
			</div>
		</section>
	</div>
}